const START_SPLITTER = '//';
const END_SPLITTER = '\\n';

const SPLITTER_LENGTH = START_SPLITTER.length;
const DELIMITER_CHARACTER_LENGTH = 1;

const START_SPLITTER_POSITION = 0;
const END_SPLITTER_POSITION =
  SPLITTER_LENGTH + DELIMITER_CHARACTER_LENGTH;

const SPLITTER_NOT_EXISTS = -1;

const CONSTANTS = {
  START_SPLITTER,
  END_SPLITTER,
  SPLITTER_LENGTH,
  DELIMITER_CHARACTER_LENGTH,
  START_SPLITTER_POSITION,
  END_SPLITTER_POSITION,
  SPLITTER_NOT_EXISTS,
};

export default CONSTANTS;
